keyframe_selector:
  gaussian_sigma: 5.0
  prominence: 0.8
  expected_keyframes: 2
  save_preview: false

visual_prompter:
  grounding_config: /opt/checkpoints/seedo/groundingdino/GroundingDINO_SwinB.cfg.py
  grounding_checkpoint: /opt/checkpoints/seedo/groundingdino/groundingdino_swinb_cogcoor.pth
  bert_model: /opt/checkpoints/seedo/bert-base-uncased
  sam_checkpoint: /opt/checkpoints/seedo/sam/sam_vit_h_4b8939.pth
  sam2_checkpoint: /opt/checkpoints/seedo/sam2/sam2_hiera_large.pt

  # Leave null to use automatic recognition via OpenAI.
  # Alternatively: "cube,cube,cube,cube,storage bin,storage bin,storage bin,storage bin"
  objects: null

action_planner:
  model: gpt-4o-2024-08-06

scene_perceiver:
  camera_calibration_path: /home/ros2_ws/src/UR5e-2f-85/zed_camera/zed_camera_calibration/estimated_camera_positions.yaml
  camera_name: zed_front
  workspace_bottom_left: [0.0, 0.0]
  workspace_top_right: [1.0, 1.0]

  detector_labels:
    - cube
    - storage bin

lmp_generator:
  model: gpt-4o-2024-08-06

scene_interpreter:
  model: gpt-4o-2024-08-06

motion_layer:
  grasp_orientation:
    - 0.9994452044624775
    - 0.03161651380119412
    - 0.0021438049655468088
    - 0.010251021036213035

  min_step: 0.02
  reach_hover_height: 0.15
  approach_z_offset: 0.0
  release_height_offset: 0.10
  lift_height: 0.15

  gripper_open_position: 0.1
  gripper_closed_position: 0.8

  object_y_offset: -0.04