defaults:
  - transform@_here_: ur5e_to_${policy_io}
  - _self_

data_components:
  workspace_rgb:
    obs_type: ${ObsType:RGB}
    repr: null
  workspace_rgb_embedding:
    obs_type: ${ObsType:VIDEO_EMBEDDING}
    repr: null
  num_conditional_frames:
    obs_type: ${ObsType:METADATA_LABEL}
    repr: null
  eef_pos_ref_delta_lowdim:
    obs_type: ${ObsType:CARTESIAN_POS}
    repr: ${LieRepr:OTHER}
  eef_rot_ref_delta_lowdim:
    obs_type: ${ObsType:CARTESIAN_POS}
    repr: ${LieRepr:OTHER}
  gripper_action_lowdim:
    obs_type: ${ObsType:BINARY_GRIPPER}
    repr: null
  eef_pos_lowdim:
    obs_type: ${ObsType:CARTESIAN_POS}
    repr: ${LieRepr:ABSOLUTE}
  eef_rot_lowdim:
    obs_type: ${ObsType:CARTESIAN_POS}
    repr: ${LieRepr:OTHER}
  gripper_lowdim:
    obs_type: ${ObsType:BINARY_GRIPPER}
    repr: null
  language_instruction:
    obs_type: ${ObsType:LANGUAGE}
    repr: null
  language_embedding:
    obs_type: ${ObsType:LANGUAGE_EMBEDDING}
    repr: null

dataset:
  _target_: cosmos_predict2.data.action.dataset_action.MimicDataset
  _convert_: partial
  data_dir: ???
  timestep_anchor: workspace_rgb
  data_components: ${..data_components}
  data_transforms: ${..data_transforms}
  source_component_names: ${..source_component_names}
  policy_io: ${policy_io.policy_io}
  should_include_padded_tails: true
  seed: 42
  num_val_episodes: 0
  validation_anchor_seed: 42
  validation_episode_sampling:
    ep_000001: first_half
    ep_000007: second_half
    ep_000055: first_half
    ep_000057: second_half
    ep_000088: first_half
    ep_000094: second_half
    ep_000126: first_half
    ep_000154: second_half
    ep_000165: first_half
    ep_000197: second_half
    ep_000202: first_half
    ep_000227: second_half
    ep_000241: first_half
    ep_000245: second_half
    ep_000293: first_half
    ep_000294: second_half
    ep_000352: first_half
    ep_000358: second_half
    ep_000361: first_half
    ep_000395: second_half
    ep_000412: first_half
    ep_000434: second_half
    ep_000454: first_half
    ep_000466: second_half
  statistics_batch_size: 4
  statistics_num_workers: 2
  statistics_prefetch_factor: 1
  episode_scan_num_workers: 2
